### ISSUE TITLE
What's the state of raylib-go in comparison to raylib?

### ISSUE THREAD

**Issue by raysan5** [gen2brain/raylib-go#20]
Hi @gen2brain, is raylib-go aligned with latest raylib 1.8? do you follow the develop branch? what's the current state?

By the way, right now I'm working on raygui module, trying to improve it...

**Comment by gen2brain** [comment]
Hi @raysan5 , yes, I updated recently C sources to 1.8 and added some new functions https://github.com/gen2brain/raylib-go/commit/0f4ce7d6d99ab0b1d73a8b90ab4d275c3644e375 . They follow develop branch. raygui is also updated, some parts, but I still didn't touch styles and renames etc.

**Comment by raysan5** [comment]
Great work @gen2brain! Thank you very much!

I think there are not many libraries out there for games dev in Go and raylib-go could be a great addition, also for learning and promoting the language. :)

**Comment by raysan5** [comment]
By the way, images (logo, screenshot) seem to be broken in the README.

**Comment by gen2brain** [comment]
Thanks! There are some good libraries, like https://github.com/oakmound/oak , https://github.com/faiface/pixel , https://github.com/hajimehoshi/ebiten etc., they all are trying to be native, in idiomatic Go, but at the end they all need OpenGL and probably OpenAL at some point, so again C is used. And compared to raylib they are much harder to use, i don't mind C like API.

raylib-go can be improved in some places, to accept []bytes instead of unsafe.Pointer for example. I also added recently helpers for Go image interface https://github.com/gen2brain/raylib-go/commit/fb585b0065c8e458b460a3f8d67c71048b9ca5d8 .

**Comment by gen2brain** [comment]
yes, images can do that sometimes, just refresh/reload should fix that, I also had to recently PURGE that from github cache, not sure why that is happening.

**Comment by raysan5** [comment]
Thanks for the answers @gen2brain! Just closing this issue!
