### ISSUE TITLE
Miscellaneous Questions

### ISSUE THREAD

**Issue by FloatingSunfish** [gen2brain/raylib-go#207]
I have some questions about `raylib-go` that I would like to understand:

1. Why are the numeric types 32-bit instead of 64-bit (e.g. `int32` instead of `int64`)?
   Is it because Go turns types like `int` into `int32` on 32-bit systems and `int64` on 64-bit systems, potentially causing problems with `raylib`?

2. I'm on Windows and build executable files using the below .bat file:

       SETLOCAL

       SET GOOS=windows
       SET GOARCH=amd64

       go build -o app_name.exe -ldflags "-H=windowsgui -s -w"

       ENDLOCAL

       cmd /k

    To build macOS executables, I try the following .bat file:

       SETLOCAL

       SET GOOS=darwin
       SET GOARCH=amd64

       go build -o app_name.app -ldflags "-H=windowsgui -s -w"

       ENDLOCAL

       cmd /k

    However, it returns the following error:

       package my_project: build constraints exclude all Go files in PATH_TO_PROJECT

    To build Linux executables, I try the following .bat file (I couldn't find how to use the `drm` build tag):

       SETLOCAL

       SET GOOS=linux
       SET GOARCH=amd64

       go build -o app_name -ldflags "-H=windowsgui -s -w"

       ENDLOCAL

       cmd /k

    However, it also returns the following error:

       package my_project: build constraints exclude all Go files in PATH_TO_PROJECT

    How do I build for Linux and macOS on Windows?

3. What's the standard for macOS executables nowadays?
   Should I use `app_name` or `app_name.app`?

**Comment by gen2brain** [comment]
1. These are C bindings, C int is 32bit so it uses `int32` in Go. The same would be with float (float32) and double (float64), or long long (int64).

2. You cannot cross-compile CGO projects just like that. When you are cross-compiling Go will by default disable CGO_ENABLED, if you enable it (you should) with CGO_ENABLED=1 you should get the error because you must use the C compiler for that architecture, usually setting CC is enough. You can see some examples here https://github.com/gen2brain/iup-go#cross-compile-linux, it is for Linux though but the same thing, in Windows you would need Linux or macOS C toolchains.

3. No, you don't name the file with .app, .app is a directory that contains files, libs, metadata, etc., you just name the regular binary.

**Comment by FloatingSunfish** [comment]
@gen2brain 
Thanks for the answers. 🙂

I'll close this Issue when I figure out or someone else posts how to compile `cgo` executables for macOS and Linux on Windows.
The link and details you provided are excellent starting points.

I want this Issue to have a solid answer for #2 before I close it so anyone else who finds it can use it as a guide.

**Comment by FloatingSunfish** [comment]
Decided to close this Issue for now.
Perhaps I will make a new question that focuses on Cross-compilation for Windows.

Currently, Zig seems to be the easiest option, though I haven't tried it yet.
