### ISSUE TITLE
[Question] Cross-compiling for Other OSes and Platforms

### ISSUE THREAD

**Issue by FloatingSunfish** [gen2brain/raylib-go#209]
A big feature of `raylib` is support for popular OSes and platforms.
Go also supports cross-compilation out of the box, but only for projects that don't use C which means `raylib-go` can't benefit from it.

How does the `raylib-go` community handle cross-compilation?
Do you guys just use VirtualBox to create different environments and build your executables there, or is there a more convenient option?

**Comment by JupiterRider** [comment]
From Linux to Windows its easy. I just need a cross-compiler ([mingw-w64-gcc](https://archlinux.org/packages/community/x86_64/mingw-w64-gcc/) in this case) and then I can build my projects with this command:
`CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 CGO_LDFLAGS="-static-libgcc -static -lpthread" go build`

Maybe you can try to use Windows Subsystem for Linux. But you will probably need X11 because its dynamically linked.
https://learn.microsoft.com/en-us/windows/wsl/
https://learn.microsoft.com/de-de/windows/wsl/tutorials/gui-apps#install-x11-apps

**Comment by FloatingSunfish** [comment]
Thanks for these! I'll give them a shot!

**Comment by JupiterRider** [comment]
@FloatingSunfish 

1. For compiling to macOS you maybe need another cross-compiler too. But I haven't done this before.
2. Yes, for Linux you just need to compile it with `go build .` and it can run on any distribution with with X11.

Oh yeah, another way would be using Github actions to "automatically" build your source.

**Comment by FloatingSunfish** [comment]
Noted, thanks @JupiterRider. 🙂

Guess there really is no "one size fits all" solution when it comes to C cross-compilation.
A shame, since it's been plaguing developers since C had to support more platforms than it was originally intended.
