### ISSUE TITLE
How to statically compile on Linux

### ISSUE THREAD

**Issue by mitjafelicijan** [gen2brain/raylib-go#243]
I am using Fedora Linux and the game is working. The issue is when I try to statically compile the binary. I get the following error.

```
$ CGO_ENABLED=1 CGO_LDFLAGS="-static-libgcc -static -lpthread" go build ./...

/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lGL: No such file or directory
/usr/bin/ld: cannot find -lm: No such file or directory
/usr/bin/ld: cannot find -lX11: No such file or directory
/usr/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status
```

I tried a bunch of things but no luck.

**Comment by mitjafelicijan** [comment]
I tried locating these libraries with `locate libm.so` and I get results.

```sh
$ locate libm.so
/usr/lib/libm.so
/usr/lib/libm.so.6
/usr/lib64/libm.so
/usr/lib64/libm.so.6
```

It found all of them:

- /usr/lib/libGL.so.1
- /usr/lib/libGL.so.1.7.0
- /usr/lib64/libGL.so
- /usr/lib64/libGL.so.1
- /usr/lib64/libGL.so.1.7.0
- /usr/lib/libm.so
- /usr/lib/libm.so.6
- /usr/lib64/libm.so
- /usr/lib64/libm.so.6
- /usr/lib/libX11.so.6
- /usr/lib/libX11.so.6.4.0
- /usr/lib64/libX11.so
- /usr/lib64/libX11.so.6
- /usr/lib64/libX11.so.6.4.0
- /usr/lib/libc.so
- /usr/lib/libc.so.6
- /usr/lib64/libc.so
- /usr/lib64/libc.so.6

I tried exporting `LD_LIBRARY_PATH` and setting compiler `CC=clang` and none of it worked. Funny is, that the program runs when I build it with `go build ./...`. But I want to statically compile the thing, so it is portable.

**Comment by gen2brain** [comment]
What you listed above are all shared libraries (`.so`), not static (`.a`). Anyway, what you are trying to do (i.e. compile a static GL app) is possible only in theory, with a lot of work with Mesa build you can probably get a static binary with software GL only. You would need to compile every possible GUI driver and link them all together. Mesa doesn't even support static builds so you would be on your own there.

If you just want a portable binary, compile it on some old system with old Glibc, and that would be just enough to make it portable.

**Comment by mitjafelicijan** [comment]
How would you advise bundling the whole thing?

I am playing around with terrain generation and I would like to avoid having to forge people to install additional stuff if I send them a binary to test.

**Comment by JupiterRider** [comment]
@mitjafelicijan aren't these libraries part of every Linux installation?

**Comment by gen2brain** [comment]
@mitjafelicijan There is not much to bundle here, Raylib does not have any external dependencies, it uses bundled single-header libraries for everything it needs, which is something I like. The final binary links only to `libc` and `libGL`. If you use `go:embed` with a combination with `FromMemory` functions to load assets, you are good to go.

My advice to compile on the old system is a general Linux recommendation, not related to Raylib. You can not compile a static GL Linux app easily, if at all, we still have `Loki Games` binaries from like 20 years ago, the only thing missing is old Glibc symbols, distributions usually use `glibc-compat` or something like that packages. That is the only thing needed to run a 20-year-old binary linked to libc and GL. The same rules work here for Raylib.

**Comment by mitjafelicijan** [comment]
So, the final boss is `libGL`. I have managed to compile all the other things, even the black magic thing of a `glibc`.

Do you maybe know where I can find `libGL`? I have been looking for it and can't find it. The only reference is found was on Sourceforge. You mentioned Loki Games. Can you point me in a direction where I could find `libgl.a` file lol.

I found this site http://www.improbability.net/loki/.

![image](https://user-images.githubusercontent.com/296714/217961957-0689da8b-de9c-4160-a5c9-fc7621a70ea3.png)

**Comment by JupiterRider** [comment]
I thought static linking of glibc in proprietary software is not allowed due to LGPL?

**Comment by gen2brain** [comment]
@JupiterRider I guess that is a common misunderstanding, LGPL is precisely what allows that, GPL would be problematic. To quote "LGPL has an exception to allow static linking without the whole code having to be under the LGPL, as long as the .o files are also distributed to allow linking with a modified glibc", and you probably don't distribute modified glibc, https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic.

But even with static binary, glibc internally calls `dlopen` for many things, e.g. if there is a `getaddrinfo` call then your static program on another system will still require `libc.so`, see https://stackoverflow.com/a/57478728. musl I believe solves this, and is recommended for static builds.

@mitjafelicijan if you are looking to "download" `libGL` from somewhere that will not get you anywhere. As I said, you can compile with many difficulties e.g. a software only libGL.a implementation that you can link to, all your users will use CPU instead of GPU, and at the end, you are getting a limited performance binary, that is actually less portable. X11 is also not recommended to compile statically (although I have done that, it is not difficult).

There are some good recommendations here https://blog.gibson.sh/2017/11/26/creating-portable-linux-binaries, anyway, for raylib-go the best is to just `go build` on system with older glibc, and that is it.
