### ISSUE TITLE
Raygui - no such file "raylib.h"

### ISSUE THREAD

**Issue by RednibCoding** [gen2brain/raylib-go#245]
When i try to run the `button example` from the examples folder, i get the following error:
```
In file included from C:\Users\mlb\go\pkg\mod\github.com\gen2brain\raylib-go\raygui@v0.0.0-20230131162822-963c891c4eb9\raygui.go:5:
./raygui.h:209:14: fatal error: raylib.h: No such file or directory
  209 |     #include "raylib.h"
      |              ^~~~~~~~~~
compilation terminated.
```

My go.mod looks as follows:
```
module raygui_playground

go 1.19

require (
	github.com/gen2brain/raylib-go/raygui v0.0.0-20230131162822-963c891c4eb9
	github.com/gen2brain/raylib-go/raylib v0.0.0-20230211191543-e394da6f5134
)
```

**Comment by JupiterRider** [comment]
Hey @RednibCoding 

I provided a fix in my cloned repo:
https://github.com/JupiterRider/raylib-go

Could you test it and tell me if it works? If so, I will provide a pull request

To test it, just clone the repo and run the example:
`git clone https://github.com/JupiterRider/raylib-go/`

`cd raylib-go\examples`

`go run gui\button\main.go`

**Comment by gen2brain** [comment]
@JupiterRider I guess that solution works if you are to clone the repo and compile GUI examples, if the user wants to actually use the raygui in the app that will not work. Well, I added the copy of `raylib.h`, so include is not an issue, now there are linking problems.

That was actually a user contribution that just looked like it is working when you test examples, we are back to the issue that I mentioned in many places, i.e. why old `raygui` was rewritten in Go, because everything needs to be duplicated. And that was exactly what I didn't have time for or wanted to do in the first place, it makes maintenance much harder. If there are no viable solutions I would prefer to remove the module.

The one "solution" would be to move raygui to raylib, but that is just the wrong thing to do as they are separate modules.

**Comment by JupiterRider** [comment]
Would it be a solution to use the raygui standalone version?
https://github.com/raysan5/raygui/blob/master/src/raygui.h#L208

**Comment by gen2brain** [comment]
Looks like something that can be tried at least, but it is not as simple as just adding define.
```
*   #define RAYGUI_STANDALONE
*       Avoid raylib.h header inclusion in this file. Data types defined on raylib are defined
*       internally in the library and **input management and drawing functions must be provided by
*       the user** (check library implementation for further details).

```
What is interesting is that I tried an example, a basic one, and now it compiles ok. GitHub actions and Ubuntu still can't link though, not sure about that.

**Comment by JupiterRider** [comment]
Yeah, for me it works now too since your last commit.

**Comment by JupiterRider** [comment]
@gen2brain I think you can close this issue.
