### ISSUE TITLE
raylib.GetKeyPressed() can not detect ENTER,TAB,BACKSPACE

### ISSUE THREAD

**Issue by cuu** [gen2brain/raylib-go#36]
git version #1418583

raylib.GetKeyPressed() can not detect ENTER,TAB,BACKSPACE 
and maybe other keys 
but raygui depends on GetKeyPressed() ,especially **TextBox** 
without BackSpace I can not even delete the chars I typed in the TextBox

After I add 
```
2739         if (key == GLFW_KEY_BACKSPACE && action == GLFW_PRESS) {
2740           lastKeyPressed = key;
2741         }
2742         if (key == GLFW_KEY_TAB && action == GLFW_PRESS) {
2743           lastKeyPressed = key;
2744         }
2745         if (key == GLFW_KEY_ENTER && action == GLFW_PRESS) {
2746           lastKeyPressed = key;
2747         }
```
in 
> 2691 static void KeyCallback(GLFWwindow *window, int key, int scancode, int action, int mods)

now it works

So is this a problem I misunderstanding or just a bug?
I am not very familiar with this cool lib

**Comment by egonelbre** [comment]
The example code in raylib uses IsKeyPressed https://github.com/raysan5/raylib/blob/master/examples/text/text_input_box.c#L55.

However looking at raylib API it looks like something that could be improved. The GetKeyPressed has a problem that it might lose characters and you might end up with a buggy text-box.

For text input you want to separate "characters" and other keys, because you have case-sensitivity and utf-8... I suspect here the `GetKeyPressed` is meant as `GetLastCharacterPressed`. You never want to mix these two, otherwise there will be pain.

For raylib the right approach would be probably to have a buffer that gets cleared each frame so that you can consume all the keys in order that happened during the frame. e.g.

```
for {
	r := raylib.GetPressedCharacter()
	if r == 0 {
		break
	}
	// ...
}
```

or the C version:

```
while(rune r = GetPressedCharacter()) { ... }
```

However this has the problem that it wouldn't be able to distinguish between characters and modifiers. There's a possibility to using something like:

```
while(input ev = GetInputEvent()){
	switch(ev.type){
	case INPUT_KEY: ...; break;
	case INPUT_CHARACTER: ...; break;
	}
}
// or 
while(input ev = GetInputEvent()){
	if(ev.key) { ... }
	if(ev.character) { ... }
}
```

How GLFW built it: http://www.glfw.org/docs/latest/input_guide.html#input_keyboard

/cc @raysan5

**Comment by cuu** [comment]
Thanks man
Now I understand,tested ,it works now ,using **IsKeyPressed**
So maybe the orig code of **raygui.go => TextBox** needs some updatings..like 

```
    if letter != -1 { 
      if letter >= 32 && letter < 127 {
        text = fmt.Sprintf("%s%c", text, letter)
      }    
    }    

    if raylib.IsKeyPressed(keyBackspaceText) {
      if len(text) > 0 {
        text = text[:len(text)-1]
      }    
    }    
```

**Comment by raysan5** [comment]
Hi @egonelbre! Thanks for the detailed report, you're right.

Actually raylib uses GLFW internally for desktop platforms, as stated `GetKeyPressed()` means `GetLastCharacterPressed()`, probably that could be improved... but it will make the code more complex...
