### ISSUE TITLE
Missing functions (core/automation_events example)

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#426]
To complete the example core/automation_events (https://www.raylib.com/examples/core/loader.html?name=core_automation_events) I need a couple of functions that seems to be missing:

    IsFileExtension
    SetAutomationEventBaseFrame

Hopefully someone can implement them eventually. I unfortunately do not know enough C to do that.

**Comment by JupiterRider** [comment]
`SetAutomationEventBaseFrame` isn't missing:
https://pkg.go.dev/github.com/gen2brain/raylib-go/raylib#SetAutomationEventBaseFrame

Instead of  `IsFileExtension` you can use `filepath.Ext`:
https://pkg.go.dev/path/filepath#Ext
If the Golang standard library already has a functionality, we often don't implement the one from raylib.

**Comment by gen2brain** [comment]
Yes, such functions as `IsFileExtension` are purposely omitted, there is no reason to bind them when there is a standard library in Go.
