### ISSUE TITLE
Why is RayMath and its types separate from its package?

### ISSUE THREAD

**Issue by Vaiktorg** [gen2brain/raylib-go#58]
@gen2brain 
I find it difficult to understand why is Vector2/3, Quaternions and Matrix structs separate from their respective math functions. 

Instead of  #`raymath.Normalize(v *raylib.Vector2) { ... &v = normval}`
Bundle all Vector2/3, Quaternions and Matrix into Raymath and pass the structs as recievers to the functions? 

Example: `func (v Vector2) Normalize() Vector2 { return normalizedVector }`

That way whenever a vector2 needs to be normalized, they don't have to be called from two different packages and just do this:
 `normVec2 := raymath.NewVector2(1,1).Normalized()`

----
 `normVec2 := raymath.NewVector2(1,1).Normalized()`
versus
`vec2 := raylib.NewVector2(1,1,1)`
`normVec2 := raymath.Normalize(vec2)`

**Comment by gen2brain** [comment]
I think there are not many examples that include raymath, couple of them maybe, so that would mean all will need to be modified to include raymath package. It is just one file, maybe it is better to be moved then to raylib package in math.go perhaps?

I thought about similar thing with raylib.Image, all functions here that accept *raylib.Image can be moved to Image struct https://godoc.org/github.com/gen2brain/raylib-go/raylib#ImageAlphaClear , but I didn't want to differ too much from C api.

**Comment by Vaiktorg** [comment]
I was thinking of doing some **_`personal`_** changes for raymath and other stray structs, to their respective packages and refactor them to make sense? I understand that you didn't want it to differ from the original API but for Go, my personal opinion is that its kinda annoying to keep referring to two different packages for a process that should be contained. I don't know.. I asked raysan for a reason why is like this, before proceeding to refactor.

**Comment by gen2brain** [comment]
If you want to work on it, I agree it is ok to move raymath.go to raylib package under math.go. raymath.go was a direct port from C to Go, nothing idiomatic. Btw, raylib C sources use raymath internally, then later is optional. I guess students that learn are fine with GetRandomValue for start.

**Comment by raysan5** [comment]
Well, in C that structure makes sense but maybe it's not the best option for Go...

raymath.h is intended not only for raylib but also be provided as external standalone library for other libraries, actually, one user used it to replace GLM library in one project...

**Comment by egonelbre** [comment]
Yeah, I would recommend merging those packages. Maybe combine with https://github.com/gen2brain/raylib-go/issues/48 to shorten the name at the same time.

**Comment by gen2brain** [comment]
Some issue that tracks all places where code can be improved to be more idiomatic can be a good start then? I will not have much time for couple of months, hired on a big project, but if everyone agrees

I will try to update C sources and do the renames, not sure about new functions. I also have a couple of changes on every C source update, nothing big, but I will try to write them this time. I enable `SUPPORT_BUSY_WAIT_LOOP` , add `// +build !noaudio` to audio.c , and I have some changes for Android, android_run instead of main, that I set then later with SetCallbackFunc.

The point is that raylib-go starts to lag compared to raylib, not all examples are rewritten now, raygui is rewritten in Go, but now too many changes happen in the meantime that I am thinking of just calling into C for that. Rres is never finished to be compatible with raylib, physics still have bug, etc. Any help about any of these is welcomed :)

**Comment by gen2brain** [comment]
Actually I disable BUSY_WAIT_LOOP, it is on by default.

**Comment by Vaiktorg** [comment]
I'll help out this weekend.

**Comment by gen2brain** [comment]
raymath is now moved to raylib package, but since now nothing is passed as the pointer I don't think there is a reason anymore to add method functions on structs.
