### ISSUE TITLE
GLFWWindow (& qt)

### ISSUE THREAD

**Issue by 5k3105** [gen2brain/raylib-go#9]
Hi,

I wanted to try using raylib with qt. To do this I would need to get the window handle and use http://doc.qt.io/qt-5/qwindow.html#setParent to embed the window.

I think this may be the window handle: 

```GLFWWindow returns a *C.GLFWwindow reference (i.e. the GLFW window itself). This can be used for passing the GLFW window handle to external C libraries.```

Could you make this available from your library? Thanks!

**Comment by raysan5** [comment]
Hi @5k3105,

Sorry but I'm afraid it's not possible, raylib uses [GLFW3](http://www.glfw.org/docs/latest/) windowing system and Qt is a completely different windowing system.

Here there are some useful references:

https://stackoverflow.com/questions/14732930/game-engine-in-opengl-with-glfw-and-qt
https://stackoverflow.com/questions/19396560/embedding-a-glfw-window-inside-windows-forms

**Comment by gen2brain** [comment]
I don't think you can use GLFWwindow just like that instead of QWindow. What you need is to find out the window id, then create window with http://doc.qt.io/qt-5/qwindow.html#fromWinId so that native window can be embedded in QWindow. SDL for example has https://wiki.libsdl.org/SDL_GetWindowID for that.

If GLFW has similar function that can be added, but currently I can just copy/update C sources from raylib, without any modification, I would not like to change C sources in such way, that would complicate updating the sources.

**Comment by 5k3105** [comment]
You are right. When I launch the process I can get the WinId. I forgot about this... or I think I was hoping there was a way to achieve this within the same program ie compile qt and raylib together instead of separately. Thanks!
